### ISSUE TITLE
loading playlists in the background

### ISSUE THREAD

**Issue by spezifisch** [spezifisch/stmps#13]
> loading playlists can take a long time on e.g. gonic if there are a lot of them; can it be done in the background?

see https://github.com/spezifisch/stmps/blob/1f8448d50bb40c5f1d519e6969b86822bd1cc464/stmps.go#L67

**Comment by xxxserxxx** [comment]
Can we close this as a dupe of #21? This one is older (original), but the other one has more metadata and information. In any case, if you merge #32, this should be closed anyway.
