### ISSUE TITLE
[BUG] DBUS MPRIS interfaces aren't named correctly

### ISSUE THREAD

**Issue by xxxserxxx** [spezifisch/stmps#22]
stmps currently shows up as "Player" in mpris clients. It should show up as "stmps." The DBUS API is obtuse at best of times, and my (limited) efforts to get the correct name while not encountering `GDBus.Error:org.freedesktop.DBus.Error.UnknownInterface: Object does not implement the interface 'org.mpris.MediaPlayer2.Player'` errors have failed.

This is a placeholder to fix this.  A successful fix would result in:

```
$ stmps -mpris
# different terminal
$ playerctl -l
stmps
$ playerctl -p stmps pause
$ echo $?
0
```

**Comment by spezifisch** [comment]
This should be fixed in `dev` branch:

```console
$ git status | head -1
On branch dev

$ playerctl -l
stmps
```

**Comment by xxxserxxx** [comment]
Yup, just found all of the changes -- while fixing them and creating a PR, of course 🙄
