### ISSUE TITLE
'a' in the Browser `Artist` tab should advance to the next item, as it does in the `Song` tab

### ISSUE THREAD

**Issue by xxxserxxx** [spezifisch/stmps#23]
UI behavior consistency. Currently, 'a' on an item in the Browser `Artist` tab adds children items to the Queue, but the cursor stays on the artist. Change this to advance to the next artist on press.

**Comment by spezifisch** [comment]
This will get fixed with #31 which is the main thing I'm working right now.

Current planned format to handle this in the new keybindings is:
```toml
[context.Browser]
a = "addArtistToQueue; cursorDown"
```

See https://github.com/spezifisch/tview-command/blob/79a67cc37b3b1ce86206b34adeed3d4deeb75e65/example.toml#L65

**Comment by xxxserxxx** [comment]
I'm going to close this as a dupe of #31.
