### ISSUE TITLE
[FEATURE] Add "show song info"

### ISSUE THREAD

**Issue by xxxserxxx** [spezifisch/stmps#25]
Add the ability to show song metadata available through the Subsonic API.

I'm thinking something like a vertical split tab in the Queue, where the currently highlighted song's metadata is shown as a simple key/value list. This would be the bare minimum; enhancements could include:

- Showing rasterized cover art
- Toggle the split

**Comment by spezifisch** [comment]
> Showing rasterized cover art

Do you notice any sluggishness when scrolling through the queue?
It takes about 1-3 seconds to select the next entry.

**Comment by xxxserxxx** [comment]
> Do you notice any sluggishness when scrolling through the queue? It takes about 1-3 seconds to select the next entry.

Hmm. I haven't. However, this would not be fork into a background process to pre-fetch  all of the images in the queue. Although it wasn't intentional, the way I implemented this with the caching should make it relatively easy to implement.

I'll add another ticket.

**Comment by spezifisch** [comment]
Reference: https://github.com/spezifisch/stmps/discussions/29

**Comment by xxxserxxx** [comment]
PR #66 should address the scrolling issues with image fetching latencies. If that's accepted and merged, this can be closed; if we want to add more stuff to the song info panel (e.g. lyrics) they should be separated tickets.
