### ISSUE TITLE
selected entry gets stuck

### ISSUE THREAD

**Issue by spezifisch** [spezifisch/stmps#33]
(`dev` branch)

I had it happen that the first song of the queue was selected, i focused the terminal and couldn't move the selected line with up/down arrows.

Workaround: Click with mouse to select another entry. First entry works normally after that.

Possibly related to the commit where the `-1` bounds check was added.

**Comment by xxxserxxx** [comment]
Can you describe the steps to reproduce this? It's not something I've come across. Which commit do you think may have caused it? I'll look into it, whether or not I introduced it :-)

Is it possible it is related to an interaction with the terminal you use, or are you able to reproduce it in other terminals?

**Comment by xxxserxxx** [comment]
@spezifisch Poke. Is this still an issue? Can you describe how to reproduce it?

**Comment by spezifisch** [comment]
> @spezifisch Poke. Is this still an issue? Can you describe how to reproduce it?

Yes, it's reproducible using mouse support in a terminal, I'm using `alacritty` but it shouldn't matter.

To reproduce:
- play a song
- click somewhere on the "Playing ... by ..." text.
- arrow keys and others get trapped because that textbox is probably now focused

This problem should be addressed through #31.

**Comment by spezifisch** [comment]
Maybe this tview method will be useful:

```go
func (b *Box) WrapMouseHandler(...)
```

**Comment by xxxserxxx** [comment]
I've reproduced it. This is a systemic problem for any widgets that don't have input handlers; it affects the song info widget as well, as it's purely informational.
