### ISSUE TITLE
Add a change log

### ISSUE THREAD

**Issue by xxxserxxx** [spezifisch/stmps#65]
With the merge of the `tviewcommand` work, old config file files become invalid, and stmps fails to start. While this should probably be addressed by config migration code, it does highlight the need for a CHANGELOG file where breaking changes can be called out for packagers and users. CHANGELOGs are generally useful for users in any case.

There's a [sort of spec for change logs](https://keepachangelog.com/en/1.0.0/). I tend to omit the preamble, and I generally disagree with the `Unreleased` format including versions, because it creates a lot of unnecessary diffs, but most importantly, I think if we use something like this, it's going to have to be mandated by you @spezifisch, b/c it's really something that's going to have to be maintained in `main`. It makes more work for the maintainer.

In any case, that's my suggestion, and FYI HEAD breaks on old config files and it isn't clear what users need to do to fix their configs without digging into the sourcecode.

**Comment by spezifisch** [comment]
> In any case, that's my suggestion, and FYI HEAD breaks on old config files and it isn't clear what users need to do to fix their configs without digging into the sourcecode.

Working on a fix.

**Comment by xxxserxxx** [comment]
> **Edit:** fixed in my dev and backported to main. Thanks for the notice.

Man, I edited that out _so_ fast after I posted it, but of course you saw it in email. I knew you were in the middle of a complex merge; I just typed faster than I thought. Always dangerous. :-)

**Comment by xxxserxxx** [comment]
There's a changelog file in the repos; we just need to keep it up to date. @spezifisch, what do you think about pulling [git-cliff](https://github.com/orhun/git-cliff) into CI and auto-generating it? Changing files in CI is odious, and could cause unnecessary conflicts and merges, but putting it in a commit hook would require everyone to have the tool installed.

In any case, the file is there; updating it isn't a "task", so I'm closing this.
